export type TemplateId = 
  | 'cafe' 
  | 'modern' 
  | 'painting' 
  | 'modern-coffee'
  | 'fast-food'
  | 'elegant-cocktail'
  | 'sweet-treats'
  | 'luxury-menu'
  | 'mena-hospitality'
  | 'borcelle-coffee'
  | 'chalkboard-coffee'
  | 'botanical-cafe'
  | 'cocktail-menu'
  | 'interactive-menu';
