"use client"
import { useMenuEditor } from "@/contexts/menu-editor-context"
import { BorcelleCoffeePreview } from "./borcelle-coffee-preview"
import { ReusableFloatingControls } from "./floating-controls"

export function BorcelleCoffeeEditor() {
  const { state, actions } = useMenuEditor()

  // Initialize with sample data if empty
  if (state.categories.length === 0) {
    const sampleCategories = [
      {
        id: "coffee",
        name: "COFFEE",
        description: "",
        items: [
          {
            id: "1",
            name: "Espresso",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "2",
            name: "Double Espresso",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "3",
            name: "Latte",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "4",
            name: "Americano",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "5",
            name: "Macchiato",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "6",
            name: "Flat White",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "7",
            name: "Cappuccino",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
      {
        id: "tea",
        name: "TEA",
        description: "",
        items: [
          {
            id: "8",
            name: "Lemon Tea",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "9",
            name: "Mango Tea",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "10",
            name: "Jasmine",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "11",
            name: "Green Tea",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "12",
            name: "Mint Tea",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
      {
        id: "non-coffee",
        name: "NON-COFFEE",
        description: "",
        items: [
          {
            id: "13",
            name: "Hot Chocolate",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "14",
            name: "Milkshake",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "15",
            name: "Smoothie",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "16",
            name: "Lemonade",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "17",
            name: "Vanilla Milkshake",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
      {
        id: "desserts",
        name: "DESSERTS",
        description: "",
        items: [
          {
            id: "18",
            name: "Strawberry Waffle",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "19",
            name: "Cinnamon Roll",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "20",
            name: "Lemon Pie",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "21",
            name: "Croissant",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "22",
            name: "Chocolate Waffle",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "23",
            name: "Brownies",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "24",
            name: "Cheesecake",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "25",
            name: "Chocolate Muffin",
            description: "",
            price: 5,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
    ]

    sampleCategories.forEach((category) => {
      actions.addCategory(category)
    })
  }

  return (
    <div className="relative">
      <BorcelleCoffeePreview />
      <ReusableFloatingControls />
    </div>
  )
}
