"use client"
import { useMenuEditor } from "@/contexts/menu-editor-context"
import { SimpleCoffeePreview } from "./simple-coffee-preview"
import { ReusableFloatingControls } from "./floating-controls"

export function SimpleCoffeeEditor() {
  const { state, actions } = useMenuEditor()

  // Initialize with sample data if empty
  if (state.categories.length === 0) {
    const sampleCategories = [
      {
        id: "espresso",
        name: "ESPRESSO",
        description: "",
        items: [
          {
            id: "1",
            name: "Americano",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "2",
            name: "Cappuccino",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "3",
            name: "Latte",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "4",
            name: "Double Espresso",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "5",
            name: "Machiato",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "6",
            name: "Mochaccino",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "7",
            name: "Long Black",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "8",
            name: "Flat White",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
      {
        id: "non-coffee",
        name: "NON-COFFEE",
        description: "",
        items: [
          {
            id: "9",
            name: "Caramel",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "10",
            name: "Coffee Jelly",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "11",
            name: "Hazelnut Mocha",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "12",
            name: "Matcha Cream",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "13",
            name: "Strawberry Cream",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "14",
            name: "Vanilla Bean",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "15",
            name: "Milkshake",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "16",
            name: "Milk Tea",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
      {
        id: "tea",
        name: "TEA",
        description: "",
        items: [
          {
            id: "17",
            name: "Hot Tea",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "18",
            name: "Ice Tea",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "19",
            name: "Lemon Tea",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "20",
            name: "Green Tea",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "21",
            name: "Jasmine Tea",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
      {
        id: "desserts",
        name: "DESSERTS",
        description: "",
        items: [
          {
            id: "22",
            name: "Strawberry Waffle",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "23",
            name: "Cinnamon Roll",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "24",
            name: "Lemon Pie",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "25",
            name: "Croissant",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
          {
            id: "26",
            name: "Chocolate Waffle",
            description: "",
            price: 4.0,
            currency: "$",
            isAvailable: true,
            isFeatured: false,
            dietaryInfo: [],
          },
        ],
      },
    ]

    sampleCategories.forEach((category) => {
      actions.addCategory(category)
    })
  }

  return (
    <div className="relative">
      <SimpleCoffeePreview />
      <ReusableFloatingControls />
    </div>
  )
}
